/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "output_self2vm_reboot_enqueue_monitor.h"
#include "Server.h"

void callback_output_self2vm_reboot_enqueue_2(const bool *n_var0)
{
    self2vm_reboot_enqueue(n_var0);
}
